### ISSUE TITLE
Falkon 3.1.0 cannot be installed

### ISSUE THREAD

**Issue by CypherNL** [dodorz/scoop-bucket#1]
> Installing 'falkon' (3.1.0) [64bit]
> De externe naam kan niet worden omgezet: 'download.kde.org'
**English:** "The external name cannot be converted: 'download.kde.org'"

> URL https://download.kde.org/stable/falkon/3.1/Falkon.Installer.3.1.0.x64.exe#/Falkon.7z is not valid

**Comment by dodorz** [comment]
It works here. Can you access the website https://kde.org/ ?

**Comment by CypherNL** [comment]
Yeah and i can now install the application. So it's resolved.
