### ISSUE TITLE
scoop install XMindZen

### ISSUE THREAD

**Issue by JingYu-Kylin** [dodorz/scoop-bucket#11]
Checking hash of XMind-ZEN-Update-2019-for-Windows-64bit-9.3.1-201909210110.exe ... ok.
Extracting dl.7z ... Could not find '$PLUGINSDIR'! (error 16)
所在位置 D:\MySoft\Scoop\apps\scoop\current\lib\core.ps1:510 字符: 9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find '$PLUGINSDIR'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find '$PLUGINSDIR'! (error 16)

**Comment by dodorz** [comment]
Thank you! I have fix it.
