### ISSUE TITLE
utools@0.8.8-beta: download via aria2 failed

### ISSUE THREAD

**Issue by crazyyy** [dodorz/scoop-bucket#19]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://resource.u-tools.cn/currentversion/uTools-0.8.8-beta.exe#/dl.7z
    referer=https://resource.u-tools.cn/currentversion/uTools-0.8.8-beta.exe#/
    dir=C:\scoop\cache
    out=utools#0.8.8-beta#https_resource.u-tools.cn_currentversion_uTools-0.8.8-beta.exe_dl.7z

ERROR & 'c:\apps\apps\aria2\current\aria2c.exe' --input-file='C:\scoop\cache\utools.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=1104 --continue

**Comment by dodorz** [comment]
Maybe you can disable aria2 and try it again.
