### ISSUE TITLE
install xpdfreader failed

### ISSUE THREAD

**Issue by weichzh** [dodorz/scoop-bucket#20]
Remove-Item : 找不到路径“C:\Users\nick\scoop\apps\xpdfreader\current\uninst.exe.nsis”，因为该路径不存在。
所在位置 行:1 字符: 1
+ Remove-Item "$dir\`$PLUGINSDIR", "$dir\uninst.exe.nsis" -Force -Recur ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\nick\s...uninst.exe.nsis:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

It should be "~\scoop\apps\xpdfreader\current\uninstall.exe.nsis"

**Comment by dodorz** [comment]
Thank you ! I have fix it. Please try again.
