### ISSUE TITLE
Hash check error for  mathpix  

### ISSUE THREAD

**Issue by intHbl** [dodorz/scoop-bucket#24]
Checking hash of mathpix_snipping_tool_setup.exe ... ERROR Hash check failed!
App:         scoop-bucket/mathpix
URL:         https://mathpix.com/win_app/mathpix_snipping_tool_setup.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    7b3eac5cd29375949b7afb8a2a2193da8fc38b159817a53d6da6e17ecde7d0de
Actual:      73ebd776cb717e136b506ebddfbe69c2e26f00510822b0dbe409a41117a60781

**Comment by dodorz** [comment]
Yes, mathpix has updated. Please `scoop update` and install it.
