### ISSUE TITLE
YoudaoDict@8.8.1.0: hash check failed

### ISSUE THREAD

**Issue by m4wayne** [dodorz/scoop-bucket#30]
Checking hash of YoudaoDict.exe ... ERROR Hash check failed!
App:         dodorz/YoudaoDict
URL:         http://cidian.youdao.com/download/YoudaoDict.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    5fb7017a437a5d171474d1ee89fef18417ace7d282408ead0ec6698434582b0f
Actual:      63874707c0ac706bb5b56b61908bd8fb0b5a57e34249659f129c0cf48a69d86d

**Comment by dodorz** [comment]
Thank you! I have fix it. Please update the bucket and try again.
