### ISSUE TITLE
chocolatey@0.10.15  & mathpix@02.01.0017: hash check failed

### ISSUE THREAD

**Issue by SiyuChen** [dodorz/scoop-bucket#31]
Installing 'chocolatey' (0.10.15) [64bit]
Starting download with aria2 ...
Download: [#f07468 0B/0B CN:1 DL:0B]
Download: [#f07468 0B/0B CN:1 DL:0B]
Download: [#f07468 0B/0B CN:1 DL:0B]
Download: [#f07468 0B/0B CN:1 DL:0B]
Download: [#f07468 0B/0B CN:1 DL:0B]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: f07468|OK  |   4.1KiB/s|C:/Users/siyu/scoop/cache/chocolatey#0.10.15#https_chocolatey.org_install.ps1
Download: Status Legend:
Download: (OK):download completed.
Checking hash of install.ps1 ... ERROR Hash check failed!
App:         dodorz/chocolatey
URL:         https://chocolatey.org/install.ps1
First bytes: 23 20 3D 3D 3D 3D 3D 3D
Expected:    1cf9d9364b2bd8748dc3038db7053e72e31382b5bac0c91afa43e86e72d9d620
Actual:      b110c2120e85ae1f33e72c7649e1d67856afae370961128e01e80a44c1116c16

WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'mathpix' (02.01.0017) [64bit]
Starting download with aria2 ...
Download: [#721da6 7.8MiB/36MiB(21%) CN:5 DL:8.9MiB ETA:3s]
Download: [#721da6 17MiB/36MiB(47%) CN:5 DL:9.3MiB ETA:2s]
Download: [#721da6 26MiB/36MiB(71%) CN:4 DL:9.1MiB ETA:1s]
Download: [#721da6 35MiB/36MiB(97%) CN:2 DL:9.2MiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 721da6|OK  |   9.1MiB/s|C:/Users/siyu/scoop/cache/mathpix#02.01.0017#https_mathpix.com_win_app_mathpix_snipping_tool_setup.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of mathpix_snipping_tool_setup.exe ... ERROR Hash check failed!
App:         dodorz/mathpix
URL:         https://mathpix.com/win_app/mathpix_snipping_tool_setup.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    1dbb7e64abbec740621987f9579df0792d41ce9a08e4e2e63e6f37538ae87715
Actual:      b07465da320b68efb621175175763cf1d8f95ad40dd430ed063296ddee6270e9

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/dodorz/scoop-bucket/issues/new?title=mathpix%4002.01.0017%3a+hash+check+failed

Could you please fix them? Cheers!

**Comment by dodorz** [comment]
Thank you! I have updated them. Please try again.
