### ISSUE TITLE
miktex@2.9.7269: download via aria2 failed

### ISSUE THREAD

**Issue by teddue** [dodorz/scoop-bucket#33]
C:\Users\teddue>scoop install miktex
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'miktex' (2.9.7269) [64bit]
Starting download with aria2 ...
Download: 03/15 21:29:36 [ERROR] CUID#8 - Download aborted. URI=https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-2.9.7269-x64.exe
Download: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://ftp.rrze.uni-erlangen.de/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-2.9.7269-x64.exe
Download:   -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 78e670|ERR |       0B/s|C:/Users/teddue/scoop/cache/miktex#2.9.7269#https_miktex.org_download_ctan_systems_win32_miktex_setup_windows-x64_basic-miktex-2.9.7269-x64.exe
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 3) Resource was not found
ERROR https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-2.9.7269-x64.exe
    referer=https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/
    dir=C:\Users\teddue\scoop\cache
    out=miktex#2.9.7269#https_miktex.org_download_ctan_systems_win32_miktex_setup_windows-x64_basic-miktex-2.9.7269-x64.exe

ERROR & 'C:\Users\teddue\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\teddue\scoop\cache\miktex.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=16368 --continue

**Comment by dodorz** [comment]
This manifest is out dated. The latest version is 2.9.7351. Please `scoop update` and try to install again.
