### ISSUE TITLE
LaTeXDraw points to wrong zip

### ISSUE THREAD

**Issue by teddue** [dodorz/scoop-bucket#35]
Installing 'latexdraw' (3.3.9) [64bit]
Starting download with aria2 ...
Download: [#dc0321 0B/0B CN:1 DL:0B]
Download: [#dc0321 96KiB/9.6MiB(0%) CN:2 DL:256KiB ETA:38s]
Download: [#dc0321 3.0MiB/9.6MiB(31%) CN:2 DL:2.2MiB ETA:3s]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: dc0321|OK  |   4.2MiB/s|C:/Users/teddue/scoop/cache/latexdraw#3.3.9#https_downloads.sourceforge.net_project_latexdraw_latexdraw_3.3.8_LaTeXDraw-3.3.8-bin.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of LaTeXDraw-3.3.8-bin.zip ... ok.
Extracting LaTeXDraw-3.3.8-bin.zip ... Could not find 'LaTeXDraw-3.3.9'! (error 16)
In C:\Users\teddue\scoop\apps\scoop\current\lib\core.ps1:510 Zeichen:9
    + throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
    +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ....9'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'LaTeXDraw-3.3.9'! (error 16)

**Comment by dodorz** [comment]
Thank you. I have fix it. Please try it again.
