### ISSUE TITLE
QQ music 启动异常

### ISSUE THREAD

**Issue by C500mg** [dodorz/scoop-bucket#36]
![qqmusic](https://user-images.githubusercontent.com/38483610/77286456-37b80d00-6d0e-11ea-973a-c6635f2cec1c.png)

**Comment by dodorz** [comment]
没办法，QQ Music用解压代替安装，不想在系统里安装它的组件就这样。不点确定也不点取消就可以一直用。

**Comment by C500mg** [comment]
好的
