### ISSUE TITLE
RRShare@3.2.5: hash check failed

### ISSUE THREAD

**Issue by TonyZZX** [dodorz/scoop-bucket#48]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 939a1a|OK  |   562KiB/s|C:/Users/tonyz/scoop/cache/RRShare#3.2.5#http_113.132.128.134_3054_YYetsShare.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of YYetsShare.exe ... ERROR Hash check failed!
App:         dodorz/RRShare
URL:         http://113.132.128.134:3054/YYetsShare.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    5c2ac4f01159cf487d480cc801e2164bc4d7b495ffd9f2462ab372cea47d8c6b
Actual:      d30163bcb3ed57ca3f363aa9d15e70f35ee1947a8fd3d501286000cb59ba9bce

**Comment by dodorz** [comment]
Thank you！I have update it. Please `scoop update` and try again.
