### ISSUE TITLE
Stellarium@0.20.2: hash check failed

### ISSUE THREAD

**Issue by leni8ec** [dodorz/scoop-bucket#49]
App:         dodorz/Stellarium
URL:         https://github.com/Stellarium/stellarium/releases/download/v0.20.2/stellarium-0.20.2-win64.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    6ab249b1ffe094f0ddfb3102a53f16f389d7fe7cd6756e47210e898b5a7863e2
Actual:      4a903c38490f627498b11a600e8ad5f5104e84aa1d3664ffc27117703d4202c9

**Comment by dodorz** [comment]
The hash is fine here. Please `scoop uninstall rm Stellarium` and try again.
