### ISSUE TITLE
".\checkver.ps1 eudic"  error

### ISSUE THREAD

**Issue by Befod** [dodorz/scoop-bucket#5]
eudic: couldn't match 'Windows ����� ([\d.]+)' in https://www.eudic.net/v4/en/app/history

**Comment by dodorz** [comment]
It works here. Can you open the website [https://www.eudic.net/](https://www.eudic.net/)?

**Comment by Befod** [comment]
yes
after `chcp 65001`
it shows `Eudic: couldn't match 'Windows 桌面版 ([\d.]+)' in https://www.eudic.net/v4/en/app/history`

**Comment by dodorz** [comment]
When you run `wget https://www.eudic.net/v4/en/app/history` and open the file in text editor, do it has the string like "Windows 桌面版 12.2.3" in it?

**Comment by Befod** [comment]
Yes，
these programs have the same problem
ViDown,Trout,YoudaoDict,Quicker,INetGet,Eudic,CloverPdf,bigrats
Maybe there's something wrong with my computer？
