### ISSUE TITLE
Everything-CLI.json needs to be updated

### ISSUE THREAD

**Issue by slbb** [dodorz/scoop-bucket#50]
The download url in mainfest is https://www.voidtools.com/es.zip
But the currect one is https://www.voidtools.com/ES-1.1.0.18.zip
Although both urls are accessable, the version I installed from scoop is missing some features.
I compare it to the version I download directly from the voidtools website, I find it's missing a `cli.c` file, and also the `es.exe` is smaller than the currect one.

**Comment by dodorz** [comment]
Thank you. I have switch to this download url. Please `scoop update` and
try again.
