### ISSUE TITLE
eudic@2020-07-10: hash check failed

### ISSUE THREAD

**Issue by Bennett-Yang** [dodorz/scoop-bucket#55]
Checking hash of eudic_win.zip ... ERROR Hash check failed!
App:         dodorz/eudic
URL:         http://static.frdic.com/pkg/eudic_win.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    60403f21d465d14503fe03b123f1660160f2f73f7828a24be262023571a89bdd
Actual:      c1262b34ccb900a55fb43a09c7be81f281268d10c86c03ee02717911c3e13c20

**Comment by dodorz** [comment]
Thank you! Eudic update their software under the table, but doesn't change version number. I have fix it.
