### ISSUE TITLE
OracleJDK11@11.0.6-8: hash check failed

### ISSUE THREAD

**Issue by huio** [dodorz/scoop-bucket#58]

**Comment by huio** [comment]
`jdk-11.0.6_windows-x64_bin.zip (4.1 KB) [==================================================================================] 100%
Checking hash of jdk-11.0.6_windows-x64_bin.zip ... ERROR Hash check failed!
App:         dodorz/OracleJDK11
URL:         https://download.oracle.com/otn/java/jdk/11.0.6+8/90eb79fb590d45c8971362673c5ab495/jdk-11.0.6_windows-x64_bin.zip
First bytes: 3C 68 74 6D 6C 3E 0A 3C
Expected:    177c6cf61cd9228b6a3d4279d94fe4eb7a5faebbc2b7a33c8c2afa9f0fdc58fb
Actual:      b729cd6d2c2aaade018b0fe303f2a454103568ea57b0306c8919722f26cfe51d

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/dodorz/scoop-bucket/issues/new?title=OracleJDK11%4011.0.6-8%3a+hash+check+failed`

**Comment by dodorz** [comment]
Thank you. It seems Oracle JDK cannot be downloaded without registration. I just remove it from repo.
