### ISSUE TITLE
Q-Dir@7.77: hash check failed

### ISSUE THREAD

**Issue by dudw** [dodorz/scoop-bucket#6]
Q-Dir: 7.76 -> 7.77
Updating one outdated app:
Updating 'Q-Dir' (7.76 -> 7.77)
Downloading new version
Q-Dir_Portable_x64.zip (1.0 MB) [==================================================================================================] 100%
Checking hash of Q-Dir_Portable_x64.zip ... ERROR Hash check failed!
App:         dodorz/Q-Dir
URL:         https://www.softwareok.com/Download/Q-Dir_Portable_x64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    ab4d15f15442a4137424a4d931795bbde39983127e7b1d0961f301eafbd1d4a6
Actual:      6689ca0f1ebb3c9eecd7367ec198b594fe1157b094ee1cf5347f9d3baf6ef84b

**Comment by dodorz** [comment]
Q-Dir has upgrade to 7.78. I have updated the manifest and please `scoop update`.
