### ISSUE TITLE
wechat@2.9.5: hash check failed

### ISSUE THREAD

**Issue by mazhenting** [dodorz/scoop-bucket#60]

**Comment by mazhenting** [comment]
App:         dodorz/wechat
URL:         https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    df512197a1d0e471a1d64d692ec0c0d101a84f02d1c6382d70677653a135a77b
Actual:      1043ba2d049733becc4dcccab7c3ce460e8d418e6af9f47049b5418f6a60bb8b

**Comment by dodorz** [comment]
Thank you! Tencent updated wechat. I have update the manifest.
Please `scoop update` and try again.

**Comment by mazhenting** [comment]
I have run it, but it seems doesn't work.

PS C:\Users\10070> scoop update
Updating Scoop...
Updating 'dodorz' bucket...
Updating 'extras' bucket...
Updating 'main' bucket...
Updating 'nonportable' bucket...
Scoop was updated successfully!
PS C:\Users\10070> scoop install wechat
Installing 'wechat' (2.9.5) [64bit]
WeChatSetup.exe (112.8 MB) [==========================================================================================] 100%
Checking hash of WeChatSetup.exe ... ERROR Hash check failed!
App:         dodorz/wechat
URL:         https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe#/dl.7z     
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    df512197a1d0e471a1d64d692ec0c0d101a84f02d1c6382d70677653a135a77b
Actual:      1043ba2d049733becc4dcccab7c3ce460e8d418e6af9f47049b5418f6a60bb8b

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/dodorz/scoop-bucket/issues/new?title=wechat%402.9.5%3a+hash+check+failed

**Comment by mazhenting** [comment]
It works, thank you.
