### ISSUE TITLE
veracrypt@1.24-Update6: decompress error

### ISSUE THREAD

**Issue by qaussie** [dodorz/scoop-bucket#61]
I am getting the following error for veracrypt 
"Failed to extract files from C:\Users\gaurav\scoop\apps\veracrypt\1.24-Update6\dl.7z.

7zip is installed. Log file attached. It is a clean install of Windows 10 with only a few  programs installed. Bitdefender is installed if this makes a difference.

[7zip.log](https://github.com/dodorz/scoop-bucket/files/4996898/7zip.log)

Scoop list shows
PS C:\Users\gaurav> scoop list
Installed apps:
  7zip 19.00
  bulk-rename-utility 3.3.2.1 [dodorz]
  ccleaner 5.69.7865 [dodorz]
  digikam 7.0.0 [extras]
  ffmpeg-nightly 20200729-cbb6ba2
  ffqueue 1.7.53 [extras]
  git 2.28.0.windows.1
  googlechrome 84.0.4147.105 [extras]
  lessmsi 1.6.91
  maxto 2.0.1 [extras]
  mp3tag 3.02 [extras]
  musicbee 3.3.7491 [extras]
  notepadplusplus 7.8.9 [extras]
  paint.net 4.2.12 [extras]
  recuva 1.53.1087 [extras]
  searchmyfiles 3.10 [nirsoft-alt]
  sharex 13.1.0 [extras]
  shutup10 1.8.1413 [extras]
  treesize-free 4.4.2 [extras]
  veracrypt 1.24-Update6 *failed*
  vlc 3.0.11 [extras]
  winscp 5.17.7 [extras]
  xnviewmp 0.96.4 [extras]
  youtube-dl 2020.07.28
  youtube-dl-gui 0.4 [extras]
  zoom 5.1.3 [extras]

any thoughts on this?

Thank you

**Comment by dodorz** [comment]
Yes, VeraCrypt can't be installed by extracting any more. I havev removed it from buckets.
