### ISSUE TITLE
geogebra@6.0.593.0:  404 download error

### ISSUE THREAD

**Issue by wicast** [dodorz/scoop-bucket#62]
```
Updating 'geogebra' (6.0.579.0 -> 6.0.593.0)
Downloading new version
远程服务器返回错误: (404) 未找到。
所在位置 D:\Program Files\Scoop\apps\scoop\current\lib\install.ps1:130 字符: 9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : 远程服务器返回错误: (404) 未找到。
```

the scoop file use url: https://download.geogebra.org/installers/6.0/GeoGebra-Windows-Portable-6-0-593-0.exe
but from https://wiki.geogebra.org/en/Reference:GeoGebra_Installation
the latest download url is down here with version 596 with zip file pack:
https://download.geogebra.org/installers/6.0/GeoGebra-Windows-Portable-6-0-596-0.zip

**Comment by dodorz** [comment]
Thank you! I have update the manifest. Please `scoop update` and try again.
