### ISSUE TITLE
Googler version 4.3.1 failed after havind uninstalled previous version

### ISSUE THREAD

**Issue by Skips75** [dodorz/scoop-bucket#69]
_sudo scoop install googler -g_  
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'googler' (4.3.1) [64bit]
Loading v4.3.1.zip from cache.
Checking hash of v4.3.1.zip ... ok.
Extracting v4.3.1.zip ... Could not find 'googler-4.2'! (error 16)
In J:\scoop\apps\scoop\current\lib\core.ps1:510 car:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find 'googler-4.2'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'googler-4.2'! (error 16)

**Comment by dodorz** [comment]
Thank you. I have fix it.
