### ISSUE TITLE
Gammadyne-CLI@1.0: hash check failed

### ISSUE THREAD

**Issue by LstHeart** [dodorz/scoop-bucket#76]

**Comment by dodorz** [comment]
It works fine here. Please type `scoop cache rm *`, `scoop update` and install it again. Thanks.

**Comment by LstHeart** [comment]
I have tried  that,but it doesn't work.
![tempsnip](https://user-images.githubusercontent.com/18585439/101275726-f3f52d00-37e2-11eb-9833-50783228cada.png)
