### ISSUE TITLE
Install notion failed

### ISSUE THREAD

**Issue by zhoutianxiang623** [dodorz/scoop-bucket#8]
Extracting notion.7z ... Could not find '$PLUGINSDIR'! (error 16)                                                       所在位置 D:\Scoop\User\apps\scoop\current\lib\core.ps1:506 字符: 9                                                      +         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...                                             +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     + CategoryInfo          : OperationStopped: (Could not find '$PLUGINSDIR'! (error 16):String) [], RuntimeException      + FullyQualifiedErrorId : Could not find '$PLUGINSDIR'! (error 16)  
![批注 2019-09-17 194212](https://user-images.githubusercontent.com/52651121/65038779-54504280-d983-11e9-8cb9-06dff93bbe8b.png)

**Comment by dodorz** [comment]
Thank you. I have fix it. Please `scoop update`.
