### ISSUE TITLE
eudic@2020-10-18: hash check failed

### ISSUE THREAD

**Issue by zippermonkey** [dodorz/scoop-bucket#82]
Installing 'eudic' (2020-10-18) [64bit]
eudic_win.zip (87.9 MB) [=====================================================================================] 100%
Checking hash of eudic_win.zip ... ERROR Hash check failed!
App:         dodorz/eudic
URL:         http://static.frdic.com/pkg/eudic_win.zip?v=version
First bytes: 50 4B 03 04 14 00 00 00
Expected:    45db6896b193936e49c62ab0ea89aa52c7139ba8779cf2dcf40f48a977991468
Actual:      aed06a5f1cbd373018cea11c0fa45163282e17d7fd87ddef9bbdedbe87f9fc14

 Hash check failed!

**Comment by dodorz** [comment]
Thank you! I've fix it. Please update & try again.
