### ISSUE TITLE
vcpkg@2020.11: hash check failed

### ISSUE THREAD

**Issue by lyandut** [dodorz/scoop-bucket#83]
App:         dodorz/vcpkg
URL:         https://github.com/microsoft/vcpkg/archive/2020.11.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    c029419cd6b559da891b59aa356d55f5100ab1d1f5a164dec1777f6020b996cb
Actual:      b89a5fac7112d067330bfb3be1ffc168d0af517ae8e5ffe3ab08825fdaa3891a

**Comment by dodorz** [comment]
It works fine here. Please `scoop update` and try agian.
