### ISSUE TITLE
eudic@2020-10-18: hash check failed

### ISSUE THREAD

**Issue by HaoyiDing** [dodorz/scoop-bucket#84]
Checking hash of eudic_win.zip ... ERROR Hash check failed!
App:         dodorz/eudic
URL:         http://static.frdic.com/pkg/eudic_win.zip?v=version
First bytes: 50 4B 03 04 14 00 00 00
Expected:    45db6896b193936e49c62ab0ea89aa52c7139ba8779cf2dcf40f48a977991468
Actual:      aed06a5f1cbd373018cea11c0fa45163282e17d7fd87ddef9bbdedbe87f9fc14

**Comment by dodorz** [comment]
Thank you! I have fix it. Please update and try again.

**Comment by HaoyiDing** [comment]
> Thank you! I have fix it. Please update and try again.

Appreciate it!
