### ISSUE TITLE
BaiduPanFilesTransfer.json is in merge conflict state

### ISSUE THREAD

**Issue by Deathnerd** [dodorz/scoop-bucket#85]
This file is causing scoop to throw an error when using `scoop search`

**Comment by Deathnerd** [comment]
Commit containing the conflict: a0f02a1ec2c89b4506372f6d9af799d28c976da3

**Comment by dodorz** [comment]
Thank you! I have fix it. Please `scoop update` and try again.

**Comment by Deathnerd** [comment]
Thanks for the quick turnaround!
