### ISSUE TITLE
quicker@1.22.26.0: hash check failed

### ISSUE THREAD

**Issue by xukecheng** [dodorz/scoop-bucket#86]
quicker: 1.12.22.0 -> 1.22.26.0
Updating one outdated app:
Updating 'quicker' (1.12.22.0 -> 1.22.26.0)
Downloading new version
Quicker.x64.1.22.26.0.msi (9.4 MB) [==========================================================================] 100%
Checking hash of Quicker.x64.1.22.26.0.msi ... ERROR Hash check failed!
App:         dodorz/quicker
URL:         https://files.getquicker.net/_productfiles/202101/Quicker.x64.1.22.26.0.msi
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    2afef0a62b2901a672c0e196142e9e5823d05918ad73354c95df9c16bfbb8a4e
Actual:      a8d7d8824a0ddb1cbdac897d05c7dc480531a379a3b2e742fc3d94c90dd199a1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/dodorz/scoop-bucket/issues/new?title=quicker%401.22.26.0%3a+hash+check+failed

**Comment by dodorz** [comment]
Thank you ! Ihave fix it. Please `scoop update` and try again.
